repos:
  # Pre-commit hooks for Python formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$|\.ipynb$'
      - id: end-of-file-fixer
        exclude: '\.ipynb$'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=50000']  # 50MB limit
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Python linting
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--strict, --ignore-missing-imports]
        exclude: '^(tests/|docs/|scripts/setup\.py)'

  # Security checking
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/, -f, json]
        exclude: 'tests/'

  # Jupyter notebook formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        args: [--line-length=88]
      - id: nbqa-isort
        args: [--profile=black]

  # Remove output from Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        entry: hadolint
        language: docker_image
        types: [dockerfile]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: '\.ipynb$'

  # Shell script checking
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck

  # Protein-specific checks
  - repo: local
    hooks:
      # Check for sensitive data in PDB files
      - id: check-pdb-privacy
        name: Check PDB files for sensitive information
        entry: scripts/check_pdb_privacy.py
        language: python
        files: '\.pdb$'
        pass_filenames: true

      # Validate protein structure files
      - id: validate-structures
        name: Validate protein structure files
        entry: scripts/validate_structures.py
        language: python
        files: '\.(pdb|cif)$'
        pass_filenames: true

      # Check model file sizes
      - id: check-model-size
        name: Check model file sizes
        entry: bash
        language: system
        files: '\.(pt|pth|ckpt|pkl)$'
        args: [-c, 'find . -name "*.pt" -o -name "*.pth" -o -name "*.ckpt" -o -name "*.pkl" | xargs ls -lh | awk "$5 > 100000000 {print $9 \" is larger than 100MB\"}"']

      # Ensure no API keys in code
      - id: check-api-keys
        name: Check for API keys and secrets
        entry: bash
        language: system
        args: [-c, 'grep -rE "(api_key|secret_key|password|token)" --include="*.py" --include="*.yml" --include="*.yaml" . || true']

# Global configuration
default_stages: [commit]
fail_fast: false

# CI-specific configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [mypy, bandit]  # Skip slow hooks in CI
  submodules: false