name: protein-operators
channels:
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
  - defaults

dependencies:
  # Python runtime
  - python=3.11
  
  # CUDA and GPU support
  - cudatoolkit=11.8
  - cudnn=8.6
  
  # Core ML frameworks
  - pytorch=2.0.*
  - torchvision
  - pytorch-cuda=11.8
  - jax=0.4.*
  - jaxlib=*=*cuda*
  
  # Scientific computing base
  - numpy=1.24.*
  - scipy=1.10.*
  - pandas=2.0.*
  - scikit-learn=1.3.*
  - h5py=3.8.*
  
  # Molecular dynamics and analysis
  - openmm=8.0.*
  - mdtraj=1.9.*
  - biopython=1.81.*
  - pymol-open-source
  
  # Visualization
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.14.*
  
  # Development tools
  - jupyter
  - ipywidgets
  - black
  - isort
  - flake8
  - mypy
  - pytest
  - pytest-cov
  - pre-commit
  
  # Build tools
  - pip
  - setuptools
  - wheel
  
  # Additional utilities
  - git
  - curl
  - wget
  
  # Pip dependencies (not available via conda)
  - pip:
    - flax>=0.7.0
    - optax>=0.1.7
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - rich>=13.0.0
    - typer>=0.9.0
    - pydantic>=2.0.0
    - py3Dmol>=2.0.0
    - mlflow>=2.3.0
    - wandb>=0.15.0
    - tensorboard>=2.13.0
    - dvc[s3]>=3.0.0
    - zarr>=2.14.0
    - datasets>=2.12.0
    - sphinx>=6.2.0
    - sphinx-rtd-theme>=1.2.0
    - myst-parser>=1.0.0
    - sphinx-autodoc-typehints>=1.23.0