apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: protein-operators
  labels:
    app: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: protein-operators

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: protein-operators
  labels:
    app: grafana

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: protein-operators
  name: grafana-role
  labels:
    app: grafana
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rolebinding
  namespace: protein-operators
  labels:
    app: grafana
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: protein-operators
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io