apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protein-operators-models
  namespace: protein-operators
  labels:
    app: protein-operators
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protein-operators-logs
  namespace: protein-operators
  labels:
    app: protein-operators
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protein-operators-data
  namespace: protein-operators
  labels:
    app: protein-operators
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp3
  volumeMode: Filesystem